#!/usr/bin/python
import argparse
import pandas as pd

parser = argparse.ArgumentParser(description='Convert Stata dta files to csv.')
parser.add_argument('infile', type=str, help='dta filename to convert')
parser.add_argument('--outfile', type=str, help='csv file to write to (default infile.csv)')
args = parser.parse_args()

outfile = args.outfile if args.outfile else (args.infile + '.csv')

data = pd.io.stata.read_stata(args.infile)
data.to_csv(outfile)